### ISSUE TITLE
Cookies to remember moon mode and token amounts entered

### ISSUE THREAD

**Issue by borgqueenx** [blocksentinel/stakeo#13]
Think this would be great for people who often visit and play around with the valuables.

**Comment by majordutch** [comment]
Hi there! Agreed, this is needed. This addition should be a relatively easy one. I have tagged this as a "good first issue" if anyone wants to give it a try. Otherwise, we will try and fit this one in soon.

**Comment by majordutch** [comment]
This feature was added in v0.8.0 and will be deployed soon. If you find any bugs, please open a new issue, thanks again!
